//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT_COMMANDE
    {
        public short ID_COMMANDE { get; set; }
        public short ID_SOCIETE { get; set; }
        public short ID_PRODUIT { get; set; }
        public short ID_PRODUIT_SOCIETE { get; set; }
        public string ETAT_PRODUIT_COMMANDE { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
        public virtual PRODUIT_SOCIETE PRODUIT_SOCIETE { get; set; }
    }
}
