//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTAIRE
    {
        [Display(Name = "Identifiant commentaire")]
        public string ID_COMMENTAIRE { get; set; }
        [Display(Name = "Identifiant utilisateur")]
        public short ID_UTILISATEUR { get; set; }
        [Display(Name = "Identifiant société")]
        public short ID_SOCIETE { get; set; }
        [Display(Name = "Identifiant produit")]
        public short ID_PRODUIT { get; set; }
        [Display(Name = "Identifiant produit société")]
        public short ID_PRODUIT_SOCIETE { get; set; }
        public short ID_SOCIETE_REL_6 { get; set; }
        [Display(Name = "Libelle")]
        public string LIBELLE_COMMENTAIRE { get; set; }
        [Display(Name = "Contenu")]
        public string CONTENU_COMMENTAIRE { get; set; }
        [Display(Name = "Date création")]
        public Nullable<System.DateTime> DATE_COMMENTAIRE { get; set; }
        [Display(Name = "Date modification")]
        public Nullable<System.DateTime> DATE_MODIFICATION_COMMENTAIRE { get; set; }
        [Display(Name = "Note")]
        public Nullable<short> NOTE_COMMENTAIRE { get; set; }
        [Display(Name = "Produit")]
        public virtual PRODUIT_SOCIETE PRODUIT_SOCIETE { get; set; }
        [Display(Name = "Société")]
        public virtual SOCIETE SOCIETE { get; set; }
        [Display(Name = "Utilisateur")]
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
