//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIEMENT
    {
        [Display(Name = "Identifiant paiement")]
        public short ID_PAIEMENT { get; set; }
        [Display(Name = "Identifiant utilisateur")]
        public Nullable<short> ID_UTILISATEUR { get; set; }
        [Display(Name = "Type carte paiement")]
        public string TYPE_CARTE_PAIEMENT { get; set; }
        [Display(Name = "Numéro carte")]
        public Nullable<int> NUMERO_CARTE_PAIEMENT { get; set; }
        [Display(Name = "Code carte")]
        public Nullable<short> CODE_CARTE_PAIEMENT { get; set; }
        [Display(Name = "Nom titulaire")]
        public string NOM_TITULAIRE_CARTE_PAIEMENT { get; set; }
        [Display(Name = "Prénom titulaire")]
        public string PRENOM_TITULAIRE_CARTE_PAIEMENT { get; set; }
        [Display(Name = "Date validité carte")]
        public Nullable<System.DateTime> DATE_VALIDITE_CARTE_PAIEMENT { get; set; }
        [Display(Name = "Adresse facturation")]
        public string ADR_FACTURATION { get; set; }
        [Display(Name = "Utilisateur")]
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
