//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUIT()
        {
            this.IMAGE = new HashSet<IMAGE>();
            this.PRODUIT_SOCIETE = new HashSet<PRODUIT_SOCIETE>();
        }
        [Display(Name = "Identifiant")]
        public short ID_PRODUIT { get; set; }
        [Display(Name = "Identifiant catégorie")]
        public Nullable<short> ID_CATEGORIE { get; set; }
        [Display(Name = "Nom")]
        public string LIBELLE_PRODUIT { get; set; }
        [Display(Name = "Description")]
        public string DESCRIPTION_PRODUIT { get; set; }
        [Display(Name = "Description technique")]
        public string DESCRIPTIF_TECHNIQUE_PRODUIT { get; set; }
        [Display(Name = "Type")]
        public string TYPE_PRODUIT { get; set; }
        [Display(Name = "Mot clés")]
        public string MOTCLE_PRODUIT { get; set; }
        [Display(Name = "Date de mise en ligne")]
        public Nullable<System.DateTime> DATE_MISE_EN_LIGNE_PRODUIT { get; set; }
        [Display(Name = "Catégorie")]
        public virtual CATEGORIE CATEGORIE { get; set; }
        [Display(Name = "Images")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGE> IMAGE { get; set; }
        [Display(Name = "Produit de la société")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUIT_SOCIETE> PRODUIT_SOCIETE { get; set; }
    }
}
