//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT_SOCIETE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUIT_SOCIETE()
        {
            this.COMMENTAIRE = new HashSet<COMMENTAIRE>();
            this.PRODUIT_COMMANDE = new HashSet<PRODUIT_COMMANDE>();
        }
    
        public short ID_SOCIETE { get; set; }
        public short ID_PRODUIT { get; set; }
        public short ID_PRODUIT_SOCIETE { get; set; }
        public string ETAT_PRODUIT { get; set; }
        public Nullable<decimal> PRIX_PRODUIT_SOCIETE { get; set; }
        public Nullable<int> STOCK_PRODUIT_SOCIETE { get; set; }
        public string DELAI_LIVRAISON_PRODUIT_SOCIETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTAIRE> COMMENTAIRE { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUIT_COMMANDE> PRODUIT_COMMANDE { get; set; }
        public virtual SOCIETE SOCIETE { get; set; }
    }
}
