//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTILISATEUR()
        {
            this.COMMANDE = new HashSet<COMMANDE>();
            this.COMMENTAIRE = new HashSet<COMMENTAIRE>();
            this.PAIEMENT = new HashSet<PAIEMENT>();
        }
    
        public short ID_UTILISATEUR { get; set; }
        public Nullable<short> ID_SOCIETE { get; set; }
        public Nullable<short> ID_VILLE { get; set; }
        [Display(Name = "Nom")]
        public string NOM_UTILISATEUR { get; set; }
        [Display(Name = "Prénom")]
        public string PRENOM_UTILISATEUR { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Veuillez saisir un email")]
        public string EMAIL_UTILISATEUR { get; set; }
        [Display(Name = "Mot de passe")]
        [Required(ErrorMessage = "Veuillez saisir un mot de passe")]
        public string MDP_UTILISATEUR { get; set; }
        [Display(Name = "Date de naissance")]
        public string DATE_NAISSANCE_UTILISATEUR { get; set; }
        [Display(Name = "Adresse")]
        public string ADR_UTILISATEUR { get; set; }
        [Display(Name = "Type de l'utilisateur")]
        public string TYPE_UTILISATEUR { get; set; }
        [Display(Name = "Droit de l'utilisateur")]
        public string DROIT_UTILISATEUR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Commandes")]
        public virtual ICollection<COMMANDE> COMMANDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Commentaires")]
        public virtual ICollection<COMMENTAIRE> COMMENTAIRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Paiement")]
        public virtual ICollection<PAIEMENT> PAIEMENT { get; set; }
        [Display(Name = "Société")]
        public virtual SOCIETE SOCIETE { get; set; }
        [Display(Name = "Ville")]
        public virtual VILLE VILLE { get; set; }
    }
}
