//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIE()
        {
            this.PRODUIT = new HashSet<PRODUIT>();
        }
        [Display(Name = "Identifiant")]
        public short ID_CATEGORIE { get; set; }
        [Display(Name = "Libellé")]
        public string LIBELLE_CATEGORIE { get; set; }
        [Display(Name = "Produits")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUIT> PRODUIT { get; set; }
    }
}
