//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMANDE()
        {
            this.PRODUIT_COMMANDE = new HashSet<PRODUIT_COMMANDE>();
        }
    
        public short ID_COMMANDE { get; set; }
        public Nullable<short> ID_UTILISATEUR { get; set; }
        public string TYPE_COMMANDE { get; set; }
        public Nullable<System.DateTime> DATE_COMMANDE { get; set; }
        public Nullable<System.DateTime> DATE_ESTIME_COMMANDE { get; set; }
        public string ADR_LIVRAISON_COMMANDE { get; set; }
        public string ETAT_COMMANDE { get; set; }
        public string LIEU_ACTUEL_COMMANDE { get; set; }
    
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUIT_COMMANDE> PRODUIT_COMMANDE { get; set; }
    }
}
