//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTAIRE
    {
        public string ID_COMMENTAIRE { get; set; }
        public short ID_UTILISATEUR { get; set; }
        public short ID_SOCIETE { get; set; }
        public short ID_PRODUIT { get; set; }
        public short ID_PRODUIT_SOCIETE { get; set; }
        public short ID_SOCIETE_REL_6 { get; set; }
        public string LIBELLE_COMMENTAIRE { get; set; }
        public string CONTENU_COMMENTAIRE { get; set; }
        public Nullable<System.DateTime> DATE_COMMENTAIRE { get; set; }
        public Nullable<System.DateTime> DATE_MODIFICATION_COMMENTAIRE { get; set; }
        public Nullable<short> NOTE_COMMENTAIRE { get; set; }
    
        public virtual PRODUIT_SOCIETE PRODUIT_SOCIETE { get; set; }
        public virtual SOCIETE SOCIETE { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
