//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        [Display(Name = "Identifiant")]
        public short ID_IMAGE { get; set; }
        [Display(Name = "Identifiant produit")]
        public short ID_PRODUIT { get; set; }
        [Display(Name = "Type")]
        public string TYPE_IMAGE { get; set; }
        [Display(Name = "Taille")]
        public string TAILLE_IMAGE { get; set; }
        [Display(Name = "Chemin")]
        public string CHEMIN_IMAGE { get; set; }
        [Display(Name = "Ordre")]
        public Nullable<byte> ORDRE_IMAGE { get; set; }
        [Display(Name = "Produit")]
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
