//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        public short ID_IMAGE { get; set; }
        public short ID_PRODUIT { get; set; }
        public string TYPE_IMAGE { get; set; }
        public string TAILLE_IMAGE { get; set; }
        public string CHEMIN_IMAGE { get; set; }
        public Nullable<byte> ORDRE_IMAGE { get; set; }
    
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
