//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT_COMMANDE
    {
        [Display(Name = "Identifiant commande")]
        public short ID_COMMANDE { get; set; }
        [Display(Name = "Identifiant société")]
        public short ID_SOCIETE { get; set; }
        [Display(Name = "Identifiant produit")]
        public short ID_PRODUIT { get; set; }
        [Display(Name = "Identifiant produit société")]
        public short ID_PRODUIT_SOCIETE { get; set; }
        [Display(Name = "Etat")]
        public string ETAT_PRODUIT_COMMANDE { get; set; }

        [Display(Name = "Commande")]
        public virtual COMMANDE COMMANDE { get; set; }
        [Display(Name = "Produit de la société")]
        public virtual PRODUIT_SOCIETE PRODUIT_SOCIETE { get; set; }
    }
}
