//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUIT()
        {
            this.IMAGE = new HashSet<IMAGE>();
            this.PRODUIT_SOCIETE = new HashSet<PRODUIT_SOCIETE>();
        }
    
        public short ID_PRODUIT { get; set; }
        public Nullable<short> ID_CATEGORIE { get; set; }
        public string LIBELLE_PRODUIT { get; set; }
        public string DESCRIPTION_PRODUIT { get; set; }
        public string DESCRIPTIF_TECHNIQUE_PRODUIT { get; set; }
        public string TYPE_PRODUIT { get; set; }
        public string MOTCLE_PRODUIT { get; set; }
        public Nullable<System.DateTime> DATE_MISE_EN_LIGNE_PRODUIT { get; set; }
    
        public virtual CATEGORIE CATEGORIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGE> IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUIT_SOCIETE> PRODUIT_SOCIETE { get; set; }
    }
}
