//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIETE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIETE()
        {
            this.COMMENTAIRE = new HashSet<COMMENTAIRE>();
            this.PRODUIT_SOCIETE = new HashSet<PRODUIT_SOCIETE>();
            this.UTILISATEUR = new HashSet<UTILISATEUR>();
        }
    
        public short ID_SOCIETE { get; set; }
        public Nullable<short> ID_VILLE { get; set; }
        public string LIBELLE_SOCIETE { get; set; }
        public string LOGO_SOCIETE { get; set; }
        public string NUMSIRET_SOCIETE { get; set; }
        public string NUMINTRA_SOCIETE { get; set; }
        public string TELEPHONE_SOCIETE { get; set; }
        public string FAX_SOCIETE { get; set; }
        public string EMAIL_SOCIETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTAIRE> COMMENTAIRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUIT_SOCIETE> PRODUIT_SOCIETE { get; set; }
        public virtual VILLE VILLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTILISATEUR> UTILISATEUR { get; set; }
    }
}
