//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class VILLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VILLE()
        {
            this.SOCIETE = new HashSet<SOCIETE>();
            this.UTILISATEUR = new HashSet<UTILISATEUR>();
        }
    
        public short ID_VILLE { get; set; }
        public short ID_PAYS { get; set; }
        public string NOM_VILLE { get; set; }
        public string CP_VILLE { get; set; }
    
        public virtual PAYS PAYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOCIETE> SOCIETE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTILISATEUR> UTILISATEUR { get; set; }
    }
}
